horda={}

horda["00000"]={
{id="00000_grupo_1",
        exp=50,
        credit=50,
        terrain="tierra",
        fondo="pradera",
        tipo="batalla",
        recompensa={"pocion", "ether"},
        enemyTeams={enemy_list["murcielago"],enemy_list["murcielago"],enemy_list["murcielago"],},
},
{id="00000_standBy_01",
        exp=100,
        credit=100,
        tipo="stand",
        terrain="tierra",
        fondo="pradera",
        recompensa={"espada","katana","espada_corta","espada_larga", "pocion", "ether"},
        enemyTeams={{}},
},
{id="00000_grupo_2",
        exp=50,
        credit=50,
        terrain="tierra",
        fondo="pradera",
        tipo="batalla",
        recompensa={"pocion", "ether"},
        enemyTeams={enemy_list["murcielago"],enemy_list["fuego_fuego"],enemy_list["murcielago"],},
},

}

NombreEspecie={["murcielago"]={name="murcielago"},
        ["slime_azul"]={name="slime azul"},
        ["murcielago_fuego"]={name="murcielago de fuego"},
        ["murcielago_hielo"]={name="murcielago de hielo"},
        ["fuego_fuego"]={name="Fuego viviente"},
        ["fuego_hielo"]={name="Fuego congelado"},
        ["fuego_electrico"]={name="Fuego electrico"},
        ["evil_eye"]={name="Ojo maldito"},
        ["slime_amarillo"]={name="slime electrico"},
        ["slime_rojo"]={name="slime de fuego"},
        ["serpiente_verde"]={name="serpiente venenosa"},
        ["Murcielago_electrico"]={name="Murcielago Electrico"},
        ["serpiente_purpura"]={name="Serpiente Toxica"},
        ["objetos"]={name="Formas"},
        ["slime_rainbow"]={name="slime arcoiris"},

}

horda["murcielago_salvaje_01"]={
{id="grupo murcielago salvaje",
        exp=50,
        credit=50,
        tipo="batalla",
        terrain="tierra",
        fondo="pradera",
        recompensa={"pocion", "ether"},
        enemyTeams={{
                name="murcielago 1",
                id="murcielago_1",
                tipo="enemy",
                id_mons="murcielago",
                x=380,
                y=160,
                x_=380,
                y_=160,
                stance="",
                modo="",
                jump_time=0,
                avanzar_time=0,
                attack_time=0,
                react_time=0,
                jump=false,
                rest=true,
                attack=false,
                avanzar=false,
                react=false,
                elemento={"aire","oscuridad","veneno"},
                weak ={fuego="fuego"},
                ventaja={volar="volar"},
                ia={"atacar"},
                p=1,
                anim={ti=0,ac=1,frm={{t=32,spr=3},{t=32,spr=32},}},
                spr=6,
                ico=32,
                lastDmg=0,
                lastDmgM="",
                lastDmgC="R",
                slDmg=false,
                live=true,                
                anim_acc="",
                anim_col={1,1,1,1},
                items={"pocion", "bomba"},
                ext=0,
                def=false,
                state={},
                tag={},
                hp=10,
                hp_=10,
                mp=5,
                mp_=5,
                sh=0,
                sh_=0,
                gl=0,
                gl_=1,
                agi=3,
                fue=3,
                con=1,
                dex=1,
                ini=0},
                {name="murcielago 2",
                id="murcielago 2",
                id_mons="murcielago",
                tipo="enemy",
	        x=420,
		y=216, 
                x_=420,
                y_=216,
                stance="",
                modo="",
                jump_time=0,
                avanzar_time=0,
                attack_time=0,
                react_time=0,
                jump=false,
                rest=true,
                attack=false,
                avanzar=false,
                react=false,
                elemento={"aire","oscuridad","veneno"},
                weak ={fuego="fuego"},
                ventaja={volar="volar"},
                ia={"atacar"},
                p=1,
                anim={ti=0,ac=1,frm={{t=32,spr=3},{t=32,spr=32},}},
                spr=6,
                ico=32,
                lastDmg=0,
                lastDmgM="",
                lastDmgC="R",
                slDmg=false,
                live=true,                
                anim_acc="",
                anim_col={1,1,1,1},
                items={"pocion", "bomba"},
                ext=0,
                def=false,
                state={},
                tag={},
                hp=10,
                hp_=10,
                mp=5,
                mp_=5,
                sh=0,
                sh_=0,
                gl=0,
                gl_=1,
                agi=3,
                fue=3,
                con=1,
                dex=1,
                ini=0},
                {name="murcielago 3",
                id="murcielago 3",
                id_mons="murcielago",
                tipo="enemy",
                x=380,
                y=272, 
                x_=380,
                y_=272,
                stance="",
                modo="",
                jump_time=0,
                avanzar_time=0,
                attack_time=0,
                react_time=0,
                jump=false,
                rest=true,
                attack=false,
                avanzar=false,
                react=false,
                elemento={"aire","oscuridad","veneno"},
                weak ={fuego="fuego"},
                ventaja={volar="volar"},
                ia={"atacar"},
                p=2,
                anim={ti=0,ac=1,frm={{t=32,spr=3},{t=32,spr=32},}},
                spr=6,
                ico=32,
                lastDmg=0,
                lastDmgM="",
                lastDmgC="R",
                slDmg=false,
                live=true,                
                anim_acc="",
                anim_col={1,1,1,1},
                items={"pocion", "bomba"},
                ext=0,
                def=false,
                state={},
                tag={},
                hp=10,
                hp_=10,
                mp=5,
                mp_=5,
                sh=0,
                sh_=0,
                gl=0,
                gl_=1,
                agi=1,
                fue=3,
                con=1,
                dex=1,
                ini=0},
                },
},
}


horda["bosque_base_01"]={
        {id="grupo 0.1",
                exp=50, credit=50, terrain="tierra", tipo="batalla",fondo="pradera",
                recompensa={"pocion", "ether"},
                enemyList={"murcielago","dummy","murcielago"},
                enemyTeams={},
        },
        
        {id="grupo 0.2",
                exp=50, credit=50, terrain="tierra", tipo="batalla",fondo="pradera",
                recompensa={"pocion", "ether"},
                enemyList={"murcielago","dummy","murcielago"},
                enemyTeams={},
        },
        
        {id="grupo 0.3",
                exp=50, credit=50, terrain="tierra", tipo="batalla",fondo="pradera",
                recompensa={"pocion", "ether"},
                enemyList={"murcielago","dummy","murcielago"},
                enemyTeams={},
        },
}

horda["bosque_base_02"]={
                {id="grupo 0.1",
                exp=50, credit=50, terrain="tierra", tipo="batalla",fondo="pradera",
                recompensa={"pocion", "ether"},
                enemyList={"murcielago","murcielago","murcielago"},
                enemyTeams={},
        },
        
        {id="grupo 0.2",
                exp=50, credit=50, terrain="tierra", tipo="batalla",fondo="pradera",
                recompensa={"pocion", "ether"},
                enemyList={"murcielago","murcielago","murcielago"},
                enemyTeams={},
        },
        
        {id="grupo 0.3",
                exp=50, credit=50, terrain="tierra", tipo="batalla",fondo="pradera",
                recompensa={"pocion", "ether"},
                enemyList={"murcielago","murcielago","murcielago"},
                enemyTeams={},
        },
}



horda["00001"]={

 {id="grupo 0.1",
        exp=50,
        credit=50,
        terrain="tierra",
        fondo="pradera",
        tipo="batalla",
        recompensa={"pocion", "ether"},
        enemyTeams={{
                name="murcielago 1",
                id="murcielago_1",
                tipo="enemy",
                id_mons="murcielago",
                x=380,
                y=160,
                x_=380,
                y_=160,
                stance="",
                modo="",
                jump_time=0,
                avanzar_time=0,
                attack_time=0,
                react_time=0,
                jump=false,
                rest=true,
                attack=false,
                avanzar=false,
                react=false,
                elemento={"normal"},
                weak ={fuego="fuego"},
                ventaja={volar="volar"},
                ia={"atacar"},
                p=1,
                anim={ti=0,ac=1,frm={{t=32,spr=3},{t=32,spr=32},}},
                spr=6,
                ico=32,
                lastDmg=0,
                lastDmgM="",
                lastDmgC="R",
                slDmg=false,
                live=true,                
                anim_acc="",
                anim_col={1,1,1,1},
                items={"pocion", "bomba"},
                ext=0,
                def=false,
                state={},
                hp=10,
                hp_=10,
                mp=5,
                mp_=5,
                sh=0,
                sh_=0,
                gl=0,
                gl_=1,
                agi=3,
                fue=3,
                con=1,
                dex=1,
                ini=0},
                {
                name="dummy_2",
                id="dummy_2",
                tipo="enemy",
                id_mons="dummy",
	        x=420,
		y=216, 
                x_=420,
                y_=216,
                jump_time=0,
                avanzar_time=0,
                jump=false,
                rest=true,
                avanzar=false,
                elemento={"normal"},
                weak ={fuego="fuego"},
                ventaja={volar="volar"},
                ia={"atacar"},
                p=2,
                anim={ti=0,ac=1,frm={{t=32,spr=140},{t=32,spr=141},}},
                spr=6,
                ico=32,
                lastDmg=0,
                lastDmgM="",
                lastDmgC="R",
                slDmg=false,
                live=true,                
                anim_acc="",
                anim_col={1,1,1,1},
                items={"pocion", "bomba"},
                ext=0,
                def=false,
                state={},
                hp=1000,
                hp_=1000,
                mp=5,
                mp_=5,
                sh=0,
                sh_=0,
                gl=0,
                gl_=1,
                agi=3,
                fue=3,
                con=1,
                dex=1,
                ini=0},
                {name="murcielago 3",
                id="murcielago 3",
                id_mons="murcielago",
                tipo="enemy",
                x=380,
                y=272, 
                x_=380,
                y_=272,
                stance="",
                modo="",
                jump_time=0,
                avanzar_time=0,
                attack_time=0,
                react_time=0,
                jump=false,
                rest=true,
                attack=false,
                avanzar=false,
                react=false,
                elemento={"normal"},
                weak ={fuego="fuego"},
                ventaja={volar="volar"},
                ia={"atacar"},
                p=3,
                anim={ti=0,ac=1,frm={{t=32,spr=3},{t=32,spr=32},}},
                spr=6,
                ico=32,
                lastDmg=0,
                lastDmgM="",
                lastDmgC="R",
                slDmg=false,
                live=true,                
                anim_acc="",
                anim_col={1,1,1,1},
                items={"pocion", "bomba"},
                ext=0,
                def=false,
                state={},
                hp=10,
                hp_=10,
                mp=5,
                mp_=5,
                sh=0,
                sh_=0,
                gl=0,
                gl_=1,
                agi=1,
                fue=3,
                con=1,
                dex=1,
                ini=0},
                },
},


        {id="grupo 0.2",
        exp=50,
        credit=50,
        tipo="batalla",
        terrain="tierra",
        fondo="pradera",
        recompensa={"pocion", "ether"},
        enemyTeams={{
                name="murcielago 1",
                id="murcielago_1",
                tipo="enemy",
                id_mons="murcielago",
                x=380,
                y=160,
                x_=380,
                y_=160,
                stance="",
                modo="",
                jump_time=0,
                avanzar_time=0,
                attack_time=0,
                react_time=0,
                jump=false,
                rest=true,
                attack=false,
                avanzar=false,
                react=false,
                elemento={"aire","oscuridad","veneno"},
                weak ={fuego="fuego"},
                ventaja={volar="volar"},
                ia={"atacar"},
                p=1,
                anim={ti=0,ac=1,frm={{t=32,spr=3},{t=32,spr=32},}},
                spr=6,
                ico=32,
                lastDmg=0,
                lastDmgM="",
                lastDmgC="R",
                slDmg=false,
                live=true,                
                anim_acc="",
                anim_col={1,1,1,1},
                items={"pocion", "bomba"},
                ext=0,
                def=false,
                state={},
                tag={},
                hp=10,
                hp_=10,
                mp=5,
                mp_=5,
                sh=0,
                sh_=0,
                gl=0,
                gl_=1,
                agi=3,
                fue=3,
                con=1,
                dex=1,
                ini=0},
                {name="murcielago 3",
                id="murcielago 3",
                id_mons="murcielago",
                tipo="enemy",
                x=380,
                y=272, 
                x_=380,
                y_=272,
                stance="",
                modo="",
                jump_time=0,
                avanzar_time=0,
                attack_time=0,
                react_time=0,
                jump=false,
                rest=true,
                attack=false,
                avanzar=false,
                react=false,
                elemento={"aire","oscuridad","veneno"},
                weak ={fuego="fuego"},
                ventaja={volar="volar"},
                ia={"atacar"},
                p=2,
                anim={ti=0,ac=1,frm={{t=32,spr=3},{t=32,spr=32},}},
                spr=6,
                ico=32,
                lastDmg=0,
                lastDmgM="",
                lastDmgC="R",
                slDmg=false,
                live=true,                
                anim_acc="",
                anim_col={1,1,1,1},
                items={"pocion", "bomba"},
                ext=0,
                def=false,
                state={},
                tag={},
                hp=10,
                hp_=10,
                mp=5,
                mp_=5,
                sh=0,
                sh_=0,
                gl=0,
                gl_=1,
                agi=1,
                fue=3,
                con=1,
                dex=1,
                ini=0},
                },
},



        {id="grupo 01",
        exp=100,
        credit=100,
        tipo="batalla",
        terrain="tierra",
        fondo="pradera",
        recompensa={"espada","katana","espada_corta","espada_larga", "pocion", "ether"},
        enemyTeams={{
                name="murcielago 1",
                id="murcielago_1",
                tipo="enemy",
                id_mons="murcielago",
                x=380,
                y=160,
                x_=380,
                y_=160,
                stance="",
                modo="",
                jump_time=0,
                avanzar_time=0,
                attack_time=0,
                react_time=0,
                jump=false,
                rest=true,
                attack=false,
                avanzar=false,
                react=false,
                elemento={"aire","oscuridad","veneno"},
                weak ={fuego="fuego"},
                ventaja={volar="volar"},
                ia={"atacar"},
                p=1,
                anim={ti=0,ac=1,frm={{t=32,spr=3},{t=32,spr=32},}},
                spr=6,
                ico=32,
                lastDmg=0,
                lastDmgM="",
                lastDmgC="R",
                slDmg=false,
                live=true,                
                anim_acc="",
                anim_col={1,1,1,1},
                items={"pocion", "bomba"},
                ext=0,
                def=false,
                state={},
                tag={},
                hp=10,
                hp_=10,
                mp=5,
                mp_=5,
                sh=0,
                sh_=0,
                gl=0,
                gl_=1,
                agi=3,
                fue=3,
                con=1,
                dex=1,
                ini=0},
                {name="murcielago fuego 2",
                id="murcielago fuego 2",
                id_mons="murcielago_fuego",
                tipo="enemy",
	        x=420,
		y=216, 
                x_=420,
                y_=216,
                stance="",
                modo="",
                jump_time=0,
                avanzar_time=0,
                attack_time=0,
                react_time=0,
                jump=false,
                rest=true,
                attack=false,
                avanzar=false,
                react=false,
                elemento={"fuego"},
                weak ={hielo="hielo",agua="agua"},
                ventaja={volar="volar",fuego="fuego"},
                ia={"atacar"},
                p=2,
                anim={ti=0,ac=1,frm={{t=32,spr=10},{t=32,spr=33},}},
                spr=36,
                ico=34,
                lastDmg=0,
                lastDmgM="",
                lastDmgC="R",
                slDmg=false,
                live=true,                
                anim_acc="",
                anim_col={1,1,1,1},
                items={"pocion", "bomba"},
                ext=0,
                def=false,
                state={},
                tag={},
                hp=10,
                hp_=10,
                mp=5,
                mp_=5,
                sh=0,
                sh_=0,
                gl=0,
                gl_=1,
                agi=1,
                fue=3,
                con=1,
                dex=1,
                ini=0},
                {name="murcielago hielo 3",
                id="murcielago hielo 3",
                id_mons="murcielago_hielo",
                tipo="enemy",
                x=380,
                y=272, 
                x_=380,
                y_=272,
                stance="",
                modo="",
                jump_time=0,
                avanzar_time=0,
                attack_time=0,
                react_time=0,
                jump=false,
                rest=true,
                attack=false,
                avanzar=false,
                react=false,
                elemento={"hielo","aire","veneno"},
                weak ={fuego="fuego",electricidad="electricidad"},
                ventaja={volar="volar",hielo="hielo",agua="agua"},
                ia={"atacar"},
                p=3,
                anim={ti=0,ac=1,frm={{t=32,spr=11},{t=32,spr=34},}},
                spr=38,
                ico=33,
                lastDmg=0,
                lastDmgM="",
                lastDmgC="R",
                slDmg=false,
                live=true,                
                anim_acc="",
                anim_col={1,1,1,1},
                items={"pocion", "bomba"},
                ext=0,
                def=false,
                state={},
                tag={},
                hp=10,
                hp_=10,
                mp=5,
                mp_=5,
                sh=0,
                sh_=0,
                gl=0,
                gl_=1,
                agi=4,
                fue=3,
                con=1,
                dex=1,
                ini=0}},
},


{
        id="grupo 2",
        exp=100,
        credit=100,
        tipo="batalla",
        terrain="cueva",
        fondo="pradera",
        recompensa={"espada","katana","espada_corta","espada_larga", "pocion", "ether"},
        enemyTeams={
                {name="fuego 1",
                id="fuego fuego 1",
                id_mons="fuego_fuego",
                tipo="enemy",
                x=380,
                y=160,
                x_=380,
                y_=160,
                stance="",
                modo="",
                jump_time=0,
                avanzar_time=0,
                attack_time=0,
                react_time=0,
                jump=false,
                rest=true,
                attack=false,
                avanzar=false,
                react=false,
                elemento={"fuego","aire","veneno"},
                weak ={hielo="hielo",agua="agua"},
                ventaja={fuego="fuego"},
                ia={"atacar"},
                p=1,
                anim={ti=0,ac=1,frm={{t=32,spr=12},{t=32,spr=14},}},
                spr=40,
                ico=35,
                lastDmg=0,
                lastDmgM="",
                lastDmgC="R",
                slDmg=false,
                live=true,                
                anim_acc="",
                anim_col={1,1,1,1},
                items={"pocion", "bomba"},
                ext=0,
                def=false,
                state={},
                tag={},
                hp=10,
                hp_=10,
                mp=5,
                mp_=5,
                sh=0,
                sh_=0,
                gl=0,
                gl_=1,
                agi=3,
                fue=3,
                con=1,
                dex=1,
                ini=0},
                {name="enemigo 2",
                id="Fuego hielito 2",
                id_mons="fuego_hielo",
                tipo="enemy",
	        x=432,
		y=216, 
                x_=432,
                y_=216,
                stance="",
                modo="",
                jump_time=0,
                avanzar_time=0,
                attack_time=0,
                react_time=0,
                jump=false,
                rest=true,
                attack=false,
                avanzar=false,
                react=false,
                elemento={"hielo"},
                weak ={fuego="fuego"},
                ventaja={volar="volar",hielo="hielo",agua="agua"},
                ia={"atacar"},
                p=2,
                anim={ti=0,ac=1,frm={{t=32,spr=13},{t=32,spr=15},}},
                spr=6,
                ico=36,
                lastDmg=0,
                lastDmgM="",
                lastDmgC="R",
                slDmg=false,
                live=true,                
                anim_acc="",
                anim_col={1,1,1,1},
                items={"pocion", "bomba"},
                ext=0,
                def=false,
                state={},
                tag={},
                hp=10,
                hp_=10,
                mp=5,
                mp_=5,
                sh=0,
                sh_=0,
                gl=0,
                gl_=1,
                agi=1,
                fue=3,
                con=1,
                dex=1,
                ini=0},
                {name="enemigo 3",
                id="fuego storm 3",
                tipo="enemy",
                id_mons="fuego_electrico",
                x=380,
                y=272, 
                x_=380,
                y_=272,
                stance="",
                modo="",
                jump_time=0,
                avanzar_time=0,
                attack_time=0,
                react_time=0,
                jump=false,
                rest=true,
                attack=false,
                avanzar=false,
                react=false,
                elemento={"electrico"},
                weak ={agua="agua",hielo="hielo"},
                ventaja={volar="volar",electricidad="electricidad"},
                ia={"atacar"},
                p=3,
                anim={ti=0,ac=1,frm={{t=32,spr=35},{t=32,spr=36},}},
                spr=42,
                ico=37,
                lastDmg=0,
                lastDmgM="",
                lastDmgC="R",
                slDmg=false,
                live=true,                
                anim_acc="",
                anim_col={1,1,1,1},
                items={"pocion", "bomba"},
                ext=0,
                def=false,
                state={},
                tag={},
                hp=10,
                hp_=10,
                mp=5,
                mp_=5,
                sh=0,
                sh_=0,
                gl=0,
                gl_=1,
                agi=4,
                fue=3,
                con=1,
                dex=1,
                ini=0}},
},
{
        id="grupo 3",
        exp=300,
        credit=300,
        tipo="batalla",
        terrain="agua",
        fondo="pradera",
        recompensa={"espada","katana","espada_corta","espada_larga", "pocion", "ether"},
        enemyTeams={
                {name="enemigo 1",
                id="enemigo 1",
                tipo="enemy",
                id_mons="murcielago",
                x=380,
                y=160,
                x_=380,
                y_=160,
                stance="",
                modo="",
                jump_time=0,
                avanzar_time=0,
                attack_time=0,
                react_time=0,
                jump=false,
                rest=true,
                attack=false,
                avanzar=false,
                react=false,
                elemento={"aire","oscuridad"},
                weak ={fuego="fuego"},
                ventaja={volar="volar"},
                ia={"atacar"},
                p=1,
                anim={ti=0,ac=1,frm={{t=32,spr=3},{t=32,spr=32},}},
                spr=6,
                ico=32,
                lastDmg=0,
                lastDmgM="",
                lastDmgC="R",
                slDmg=false,
                live=true,                
                anim_acc="",
                anim_col={1,1,1,1},
                items={"pocion", "bomba"},
                ext=0,
                def=false,
                state={},
                tag={},
                hp=10,
                hp_=10,
                mp=5,
                mp_=5,
                sh=0,
                sh_=0,
                gl=0,
                gl_=1,
                agi=3,
                fue=3,
                con=1,
                dex=1,
                ini=0},
                {name="BOSS",
                id="BOSS",
                id_mons="evil_eye",
                tipo="enemy",
	        x=430,
		y=216, 
                x_=430,
                y_=216,
                stance="",
                modo="",
                jump_time=0,
                avanzar_time=0,
                attack_time=0,
                react_time=0,
                jump=false,
                rest=true,
                attack=false,
                avanzar=false,
                react=false,
                elemento={"oscuridad"},
                weak ={fuego="fuego",electricidad="electricidad"},
                ventaja={},
                prof={},
                ia={"atacar"},
                p=2,
                anim={ti=0,ac=1,frm={{t=32,spr=37},{t=32,spr=38},}},
                spr=6,
                ico=38,
                lastDmg=0,
                lastDmgM="",
                lastDmgC="R",
                slDmg=false,
                live=true,                
                anim_acc="",
                anim_col={1,1,1,1},
                items={"pocion", "bomba"},
                ext=0,
                def=false,
                state={},
                tag={},
                hp=40,
                hp_=40,
                mp=5,
                mp_=5,
                sh=2,
                sh_=2,
                gl=0,
                gl_=1,
                agi=9,
                fue=3,
                con=1,
                dex=1,
                ini=0},
                {name="enemigo 3",
                id="enemigo 3",
                tipo="enemy",
                id_mons="murcielago",
                x=380,
                y=272, 
                x_=380,
                y_=272,
                stance="",
                modo="",
                jump_time=0,
                avanzar_time=0,
                attack_time=0,
                react_time=0,
                jump=false,
                rest=true,
                attack=false,
                avanzar=false,
                react=false,
                elemento={"oscuridad","aire","veneno"},
                weak ={fuego="fuego"},
                ventaja={volar="volar"},
                ia={"atacar","veneno","drenar"},
                p=3,
                anim={ti=0,ac=1,frm={{t=32,spr=3},{t=32,spr=32},}},
                spr=6,
                ico=32,
                lastDmg=0,
                lastDmgM="",
                lastDmgC="R",
                slDmg=false,
                live=true,
                anim_acc="",
                anim_col={1,1,1,1},
                items={"pocion", "bomba"},
                ext=0,
                def=false,
                state={},
                tag={},
                hp=10,
                hp_=10,
                mp=5,
                mp_=5,
                sh=0,
                sh_=0,
                gl=0,
                gl_=1,
                agi=4,
                fue=3,
                con=1,
                dex=1,
                ini=0}},
},

{id="standBy 01",
        exp=100,
        credit=100,
        tipo="stand",
        terrain="tierra",
        fondo="pradera",
        recompensa={"espada","katana","espada_corta","espada_larga", "pocion", "ether"},
        enemyTeams={{}},
},

{
        id="grupo 4",
        exp=100,
        credit=100,
        tipo="batalla",
        terrain="pladera",
        fondo="pradera",
        recompensa={"espada","katana","espada_corta","espada_larga", "pocion", "ether"},
        enemyTeams={
                {name="slime azul",
                id="slime azul",
                id_mons="slime_azul",
                tipo="enemy",
                x=380,
                y=160,
                x_=380,
                y_=160,
                stance="",
                modo="",
                jump_time=0,
                avanzar_time=0,
                attack_time=0,
                react_time=0,
                jump=false,
                rest=true,
                attack=false,
                avanzar=false,
                react=false,
                elemento={"agua"},
                weak ={fuego="fuego",electricidad="electricidad",hielo="hielo"},
                ventaja={volar="volar"},
                ia={"atacar"},
                p=1,
                anim={ti=0,ac=1,frm={{t=32,spr=70},{t=32,spr=71},}},
                spr=6,
                ico=32,
                lastDmg=0,
                lastDmgM="",
                lastDmgC="R",
                slDmg=false,
                live=true,
                anim_acc="",
                anim_col={1,1,1,1},
                items={"pocion", "bomba"},
                ext=0,
                def=false,
                state={},
                tag={},
                hp=8,
                hp_=8,
                mp=5,
                mp_=5,
                sh=0,
                sh_=0,
                gl=0,
                gl_=1,
                agi=3,
                fue=3,
                con=1,
                dex=1,
                ini=0},
                {name="slime amarillo",
                id="slime amarillo",
                id_mons="slime_amarillo",
                tipo="enemy",
	        x=450,
		y=216, 
                x_=450,
                y_=216,
                stance="",
                modo="",
                jump_time=0,
                avanzar_time=0,
                attack_time=0,
                react_time=0,
                jump=false,
                rest=true,
                attack=false,
                avanzar=false,
                react=false,
                elemento={"electrico","agua"},
                weak ={fuego="fuego",electricidad="electricidad",hielo="hielo"},
                ventaja={},
                prof={},
                ia={"atacar"},
                p=2,
                anim={ti=0,ac=1,frm={{t=32,spr=72},{t=32,spr=73},}},
                spr=6,
                ico=38,
                lastDmg=0,
                lastDmgM="",
                lastDmgC="R",
                anim_acc="",
                anim_col={1,1,1,1},
                slDmg=false,
                live=true,
                items={"pocion", "bomba"},
                ext=0,
                def=false,
                state={},
                tag={},
                hp=8,
                hp_=8,
                mp=5,
                mp_=5,
                sh=0,
                sh_=0,
                gl=0,
                gl_=1,
                agi=9,
                fue=3,
                con=1,
                dex=1,
                ini=0},
                {name="slime rojo",
                id="slime rojo",
                id_mons="slime_rojo",
                tipo="enemy",
                x=380,
                y=272, 
                x_=380,
                y_=272,
                stance="",
                modo="",
                jump_time=0,
                avanzar_time=0,
                attack_time=0,
                react_time=0,
                jump=false,
                rest=true,
                attack=false,
                avanzar=false,
                react=false,
                elemento={"fuego","agua"},
                weak ={fuego="fuego",electricidad="electricidad",hielo="hielo"},
                ventaja={},
                prof={},
                ia={"atacar"},
                p=3,
                anim={ti=0,ac=1,frm={{t=32,spr=74},{t=32,spr=75},}},
                spr=6,
                ico=32,
                lastDmg=0,
                lastDmgM="",
                lastDmgC="R",
                anim_acc="",
                anim_col={1,1,1,1},
                slDmg=false,
                live=true,
                items={"pocion", "bomba"},
                ext=0,
                def=false,
                state={},
                tag={},
                hp=8,
                hp_=8,
                mp=5,
                mp_=5,
                sh=0,
                sh_=0,
                gl=0,
                gl_=1,
                agi=4,
                fue=3,
                con=1,
                dex=1,
                ini=0}},
        },


        {
        id="grupo 5",
        exp=100,
        credit=100,
        tipo="batalla",
        terrain="cueva",
        fondo="pradera",
        recompensa={"espada","katana","espada_corta","espada_larga", "pocion", "ether"},
        enemyTeams={
                {name="serpiente verde",
                id="serpiente verde 1",
                id_mons="serpiente_verde",
                tipo="enemy",
                x=380,
                y=160,
                x_=380,
                y_=160,
                stance="",
                modo="",
                jump_time=0,
                avanzar_time=0,
                attack_time=0,
                react_time=0,
                jump=false,
                rest=true,
                attack=false,
                avanzar=false,
                react=false,
                elemento={"tierra","veneno"},
                weak ={fuego="fuego"},
                ventaja={},
                prof={},
                ia={"atacar"},
                p=1,
                anim={ti=0,ac=1,frm={{t=32,spr=66},{t=32,spr=67},}},
                spr=6,
                ico=32,
                lastDmg=0,
                lastDmgM="",
                lastDmgC="R",
                slDmg=false,
                live=true,
                anim_acc="",
                anim_col={1,1,1,1},
                items={"pocion", "bomba"},
                ext=0,
                def=false,
                state={},
                tag={},
                hp=16,
                hp_=16,
                mp=5,
                mp_=5,
                sh=0,
                sh_=0,
                gl=0,
                gl_=1,
                agi=3,
                fue=3,
                con=1,
                dex=1,
                ini=0},
                {name="Murcielago electrico",
                id="Murcielago electrico 2",
                id_mons="Murcielago_electrico",
                tipo="enemy",
	        x=420,
		y=216, 
                x_=420,
                y_=216,
                stance="",
                modo="",
                jump_time=0,
                avanzar_time=0,
                attack_time=0,
                react_time=0,
                jump=false,
                rest=true,
                attack=false,
                avanzar=false,
                react=false,
                elemento={"aire","veneno","electrico"},
                weak ={fuego="nada",agua="agua"},
                ventaja={volar="nada"},
                ia={"atacar"},
                p=2,
                anim={ti=0,ac=1,frm={{t=32,spr=64},{t=32,spr=65},}},
                spr=6,
                ico=38,
                lastDmg=0,
                lastDmgM="",
                lastDmgC="R",
                slDmg=false,
                live=true,
                anim_acc="",
                anim_col={1,1,1,1},
                items={"pocion", "bomba"},
                ext=0,
                def=false,
                state={},
                tag={},
                hp=10,
                hp_=10,
                mp=5,
                mp_=5,
                sh=0,
                sh_=0,
                gl=0,
                gl_=1,
                agi=9,
                fue=3,
                con=1,
                dex=1,
                ini=0},
                {name="serpiente purpura",
                id="serpiente purpura 3",
                id_mons="serpiente_purpura",
                tipo="enemy",
                x=380,
                y=272, 
                x_=380,
                y_=272,
                stance="",
                modo="",
                jump_time=0,
                avanzar_time=0,
                attack_time=0,
                react_time=0,
                jump=false,
                rest=true,
                attack=false,
                avanzar=false,
                react=false,
                elemento={"tierra","veneno"},
                weak ={fuego="fuego"},
                ventaja={},
                prof={},
                ia={"atacar"},
                p=3,
                anim={ti=0,ac=1,frm={{t=32,spr=68},{t=32,spr=69},}},
                spr=6,
                ico=32,
                lastDmg=0,
                lastDmgM="",
                lastDmgC="R",
                slDmg=false,
                live=true,
                anim_acc="",
                anim_col={1,1,1,1},
                items={"pocion", "bomba"},
                ext=0,
                def=false,
                state={},
                tag={},
                hp=16,
                hp_=16,
                mp=5,
                mp_=5,
                sh=0,
                sh_=0,
                gl=0,
                gl_=1,
                agi=4,
                fue=3,
                con=1,
                dex=1,
                ini=0}},
        },


        {
        id="grupo 6",
        exp=100,
        credit=100,
        tipo="batalla",
        terrain="agua",
        fondo="pradera",
        recompensa={"espada","katana","espada_corta","espada_larga", "pocion", "ether"},
        enemyTeams={
                {name="objetos 1",
                id="objetos 1",
                id_mons="objetos",
                tipo="enemy",
                x=380,
                y=160,
                x_=380,
                y_=160,
                stance="",
                modo="",
                jump_time=0,
                avanzar_time=0,
                attack_time=0,
                react_time=0,
                jump=false,
                rest=true,
                attack=false,
                avanzar=false,
                react=false,
                elemento={"aire","magia"},
                weak ={electricidad="electricidad"},
                ventaja={volar="volar"},
                ia={"atacar"},
                p=1,
                anim={ti=0,ac=1,frm={{t=32,spr=76},{t=32,spr=77},}},
                spr=6,
                ico=32,
                lastDmg=0,
                lastDmgM="",
                lastDmgC="R",
                slDmg=false,
                live=true,
                anim_acc="",
                anim_col={1,1,1,1},
                items={"pocion", "bomba"},
                ext=0,
                def=false,
                state={},
                tag={},
                hp=20,
                hp_=20,
                mp=5,
                mp_=5,
                sh=1,
                sh_=1,
                gl=0,
                gl_=1,
                agi=3,
                fue=3,
                con=1,
                dex=1,
                ini=0},
                {name="slime arcoiris",
                id="slime arcoiris",
                id_mons="slime_rainbow",
                tipo="enemy",
	        x=446,
		y=216, 
                x_=446,
                y_=216,
                stance="",
                modo="",
                jump_time=0,
                avanzar_time=0,
                attack_time=0,
                react_time=0,
                jump=false,
                rest=true,
                attack=false,
                avanzar=false,
                react=false,
                elemento={"agua","fuego","electrico"},
                weak ={fuego="fuego",electricidad="electricidad",hielo="hielo"},
                ventaja={volar="nada"},
                ia={"atacar"},
                p=2,
                anim={ti=0,ac=1,frm={{t=32,spr=73},{t=32,spr=74},}},
                spr=6,
                ico=38,
                lastDmg=0,
                lastDmgM="",
                lastDmgC="R",
                slDmg=false,
                live=true,
                anim_acc="",
                anim_col={1,1,1,1},
                items={"pocion", "bomba"},
                ext=0,
                def=false,
                state={},
                tag={},
                hp=16,
                hp_=16,
                mp=5,
                mp_=5,
                sh=1,
                sh_=1,
                gl=0,
                gl_=1,
                agi=9,
                fue=3,
                con=1,
                dex=1,
                ini=0},
                {name="objetos 2",
                id="objetos 2",
                id_mons="objetos",
                tipo="enemy",
                x=380,
                y=272, 
                x_=380,
                y_=272,
                stance="",
                modo="",
                jump_time=0,
                avanzar_time=0,
                attack_time=0,
                react_time=0,
                jump=false,
                rest=true,
                attack=false,
                avanzar=false,
                react=false,
                elemento={"aire","magia"},
                weak ={electricidad="electricidad"},
                ventaja={volar="volar"},
                ia={"atacar"},
                p=3,
                anim={ti=0,ac=1,frm={{t=32,spr=76},{t=32,spr=77},}},
                spr=6,
                ico=32,
                lastDmg=0,
                lastDmgM="",
                lastDmgC="R",
                slDmg=false,
                live=true,
                anim_acc="",
                anim_col={1,1,1,1},
                items={"pocion", "bomba"},
                ext=0,
                def=false,
                state={},
                tag={},
                hp=20,
                hp_=20,
                mp=5,
                mp_=5,
                sh=1,
                sh_=1,
                gl=0,
                gl_=1,
                agi=4,
                fue=3,
                con=1,
                dex=1,
                ini=0}},
        },

        {id="standBy 02",
        exp=100,
        credit=100,
        tipo="stand",
        terrain="tierra",
        recompensa={"espada","katana","espada_corta","espada_larga", "pocion", "ether"},
        enemyTeams={{}},
        },
}

enemyGroups=horda["00001"]




