horda={}

horda["00000"]={
{id="00000_grupo_1",
        exp=50,
        credit=50,
        terrain="tierra",
        terrain_="tierra",
        fondo="pradera",
        fondo_="pradera",
        tipo="batalla",
        recompensa={"pocion", "ether"},
        enemyList={"murcielago","murcielago","murcielago"},
        enemyTeams={},
},
{id="00000_standBy_01",
        exp=100,
        credit=100,
        tipo="stand",
        terrain="tierra",
        terrain_="tierra",
        fondo="pradera",
        fondo_="pradera",
        recompensa={"espada","katana","espada_corta","espada_larga", "pocion", "ether"},
        enemyList={"murcielago","murcielago","murcielago"},
        enemyTeams={},
},
{id="00000_grupo_2",
        exp=50,
        credit=50,
        terrain="tierra",
        terrain_="tierra",
        fondo="pradera",
        fondo_="pradera",
        tipo="batalla",
        recompensa={"pocion", "ether"},
        enemyList={"murcielago","fuego_fuego","murcielago"},
        enemyTeams={},
},

}

NombreEspecie={["murcielago"]={name="murcielago"},
        ["slime_azul"]={name="slime azul"},
        ["murcielago_fuego"]={name="murcielago de fuego"},
        ["murcielago_hielo"]={name="murcielago de hielo"},
        ["fuego_fuego"]={name="Fuego viviente"},
        ["fuego_hielo"]={name="Fuego congelado"},
        ["fuego_electrico"]={name="Fuego electrico"},
        ["evil_eye"]={name="Ojo maldito"},
        ["slime_amarillo"]={name="slime electrico"},
        ["slime_rojo"]={name="slime de fuego"},
        ["serpiente_verde"]={name="serpiente venenosa"},
        ["Murcielago_electrico"]={name="Murcielago Electrico"},
        ["serpiente_purpura"]={name="Serpiente Toxica"},
        ["objetos"]={name="Formas"},
        ["slime_rainbow"]={name="slime arcoiris"},

}

horda["murcielago_salvaje_01"]={
{id="grupo murcielago salvaje",
        exp=50,
        credit=50,
        tipo="batalla",
        terrain="pradera",
        terrain_="pradera",
        fondo="pradera",
        fondo_="pradera",
        recompensa={"pocion", "ether"},
        enemyList={"murcielago","dummy","murcielago"},
        enemyTeams={},
},
}


horda["bosque_base_01"]={
        {id="grupo 0.1",
                exp=50, credit=50, terrain="pradera", terrain_="pradera", tipo="batalla",fondo="pradera", fondo_="pradera",
                recompensa={"pocion", "ether"},
                enemyList={"murcielago","dummy","murcielago"},
                enemyTeams={},
        },
        
        {id="grupo 0.2",
                exp=50, credit=50, terrain="tierra", terrain_="tierra",tipo="batalla",fondo="pradera",
                recompensa={"pocion", "ether"},
                enemyList={"murcielago","dummy","murcielago"},
                enemyTeams={},
        },
        
        {id="grupo 0.3",
                exp=50, credit=50, terrain="tierra", terrain_="tierra",tipo="batalla",fondo="pradera",
                recompensa={"pocion", "ether"},
                enemyList={"murcielago","dummy","murcielago"},
                enemyTeams={},
        },
}

horda["bosque_base_02"]={
                {id="grupo 0.1",
                exp=50, credit=50, terrain="tierra", terrain_="tierra",tipo="batalla",fondo="pradera",
                recompensa={"pocion", "ether"},
                enemyList={"murcielago","murcielago","murcielago"},
                enemyTeams={},
        },
        
        {id="grupo 0.2",
                exp=50, credit=50, terrain="tierra", terrain_="tierra",tipo="batalla",fondo="pradera",
                recompensa={"pocion", "ether"},
                enemyList={"murcielago","murcielago","murcielago"},
                enemyTeams={},
        },
        
        {id="grupo 0.3",
                exp=50, credit=50, terrain="tierra", terrain_="tierra",tipo="batalla",fondo="pradera",
                recompensa={"pocion", "ether"},
                enemyList={"murcielago","murcielago","murcielago"},
                enemyTeams={},
        },
}



horda["00001"]={

 {id="grupo 0.1",
        exp=50,
        credit=50,
        terrain="agua",
        terrain_="agua",
        tipo="batalla",
        fondo="ocean",
        fondo_="ocean",
        recompensa={"pocion", "ether"},
        enemyList={"murcielago","murcielago"},
        enemyTeams={},
},


        {id="grupo 0.2",
        exp=50,
        credit=50,
        tipo="batalla",
        terrain="tierra",
        terrain_="tierra",
        fondo="pradera",
        fondo_="pradera",
        recompensa={"pocion", "ether"},
        enemyList={"murcielago","murcielago","murcielago"},
        enemyTeams={},
},



        {id="grupo 01",
        exp=100,
        credit=100,
        tipo="batalla",
        terrain="pladera",
        terrain_="pladera",
        fondo="pradera",
        fondo_="pradera",
        recompensa={"espada","katana","espada_corta","espada_larga", "pocion", "ether"},
        enemyList={"murcielago","murcielago_fuego","murcielago_hielo"},
        enemyTeams={},
},


{
        id="grupo 2",
        exp=100,
        credit=100,
        tipo="batalla",
        terrain="cueva",
        terrain_="cueva",
        fondo="cueva",
        fondo_="cueva",
        recompensa={"espada","katana","espada_corta","espada_larga", "pocion", "ether"},
        enemyList={"fuego_fuego","fuego_hielo","fuego_electrico"},
        enemyTeams={},
},
{
        id="grupo 3",
        exp=300,
        credit=300,
        tipo="batalla",
        terrain="agua",
        terrain_="agua",
        fondo="ocean",
        fondo_="ocean",
        recompensa={"espada","katana","espada_corta","espada_larga", "pocion", "ether"},
        enemyList={"murcielago","evil_eye","murcielago"},
        enemyTeams={},
},

{id="standBy 01",
        exp=100,
        credit=100,
        tipo="stand",
        terrain="tierra",
        terrain_="tierra",
        fondo="pradera",
        fondo_="pradera",
        recompensa={"espada","katana","espada_corta","espada_larga", "pocion", "ether"},
        enemyList={},
        enemyTeams={},
},

{
        id="grupo 4",
        exp=100,
        credit=100,
        tipo="batalla",
        terrain="pladera",
        terrain_="pladera",
        fondo="pradera",
        fondo_="pradera",
        recompensa={"espada","katana","espada_corta","espada_larga", "pocion", "ether"},
        enemyList={"slime_azul","slime_amarillo","slime_rojo"},
        enemyTeams={},
        },


        {
        id="grupo 5",
        exp=100,
        credit=100,
        tipo="batalla",
        terrain="cueva",
        terrain_="cueva",
        fondo="pradera",
        fondo_="pradera",
        recompensa={"espada","katana","espada_corta","espada_larga", "pocion", "ether"},
        enemyList={"serpiente_verde","Murcielago_electrico","serpiente_purpura"},
        enemyTeams={},
        },


        {
        id="grupo 6",
        exp=100,
        credit=100,
        tipo="batalla",
        terrain="agua",
        terrain_="agua",
        fondo="pradera",
        fondo_="pradera",
        recompensa={"espada","katana","espada_corta","espada_larga", "pocion", "ether"},
        enemyList={"objetos","slime_rainbow","objetos"},
        enemyTeams={},
        },

        {id="standBy 02",
        exp=100,
        credit=100,
        tipo="stand",
        terrain="tierra",
        terrain_="tierra",
        fondo="pradera",
        fondo_="pradera",
        recompensa={"espada","katana","espada_corta","espada_larga", "pocion", "ether"},
        enemyList={},
        enemyTeams={{}},
        },
}

enemyGroups=horda["00001"]




