horda={}

horda["00000"]={
{id="00000_grupo_1",
        exp=50,
        credit=50,
        terrain="pradera",
        terrain_="pradera",
        fondo="pradera",
        fondo_="pradera",
        tipo="batalla",
        recompensa={"pocion", "ether"},
        enemyTeams={enemy_list["murcielago"],enemy_list["murcielago"],enemy_list["murcielago"],},
},
{id="00000_standBy_01",
        exp=100,
        credit=100,
        tipo="stand",
        terrain="tierra",
        terrain_="tierra",
        fondo="pradera",
        fondo_="pradera",
        recompensa={"espada","katana","espada_corta","espada_larga", "pocion", "ether"},
        enemyTeams={{}},
},
{id="00000_grupo_2",
        exp=50,
        credit=50,
        terrain="tierra",
        terrain_="tierra",
        fondo="pradera",
        fondo_="pradera",
        tipo="batalla",
        recompensa={"pocion", "ether"},
        enemyTeams={enemy_list["murcielago"],enemy_list["fuego_fuego"],enemy_list["murcielago"],},
},

}

NombreEspecie={["murcielago"]={name="murcielago"},
        ["slime_azul"]={name="slime azul"},
        ["murcielago_fuego"]={name="murcielago de fuego"},
        ["murcielago_hielo"]={name="murcielago de hielo"},
        ["fuego_fuego"]={name="Fuego viviente"},
        ["fuego_hielo"]={name="Fuego congelado"},
        ["fuego_electrico"]={name="Fuego electrico"},
        ["evil_eye"]={name="Ojo maldito"},
        ["slime_amarillo"]={name="slime electrico"},
        ["slime_rojo"]={name="slime de fuego"},
        ["serpiente_verde"]={name="serpiente venenosa"},
        ["Murcielago_electrico"]={name="Murcielago Electrico"},
        ["serpiente_purpura"]={name="Serpiente Toxica"},
        ["objetos"]={name="Formas"},
        ["slime_rainbow"]={name="slime arcoiris"},

}

horda["murcielago_salvaje_01"]={
{id="grupo murcielago salvaje",
        exp=50,
        credit=50,
        tipo="batalla",
        terrain="pradera",
        terrain_="pradera",
        fondo="pradera",
        fondo_="pradera",
        recompensa={"pocion", "ether"},
        enemyTeams={{
                name="murcielago 1",
                id="murcielago_1",
                tipo="enemy",
                id_mons="murcielago",
                x=380,
                y=160,
                x_=380,
                y_=160,
                stance="",
                modo="",
                jump_time=0,
                avanzar_time=0,
                attack_time=0,
                react_time=0,
                jump=false,
                rest=true,
                attack=false,
                avanzar=false,
                react=false,
                elemento={"aire","oscuridad","veneno"},
                weak ={fuego="fuego"},
                ventaja={volar="volar"},
                ia={"atacar"},
                p=1,
                anim={ti=0,ac=1,frm={{t=32,spr=3},{t=32,spr=32},}},
                spr=6,
                ico=32,
                lastDmg=0,
                lastDmgM="",
                lastDmgC="R",
                slDmg=false,
                live=true,                
                anim_acc="",
                anim_col={1,1,1,1},
                items={"pocion", "bomba"},
                ext=0,
                def=false,
                state={},
                tag={},
                hp=10,
                hp_=10,
                mp=5,
                mp_=5,
                sh=0,
                sh_=0,
                gl=0,
                gl_=1,
                agi=3,
                fue=3,
                con=1,
                dex=1,
                ini=0},
                {name="murcielago 2",
                id="murcielago 2",
                id_mons="murcielago",
                tipo="enemy",
	        x=420,
		y=216, 
                x_=420,
                y_=216,
                stance="",
                modo="",
                jump_time=0,
                avanzar_time=0,
                attack_time=0,
                react_time=0,
                jump=false,
                rest=true,
                attack=false,
                avanzar=false,
                react=false,
                elemento={"aire","oscuridad","veneno"},
                weak ={fuego="fuego"},
                ventaja={volar="volar"},
                ia={"atacar"},
                p=1,
                anim={ti=0,ac=1,frm={{t=32,spr=3},{t=32,spr=32},}},
                spr=6,
                ico=32,
                lastDmg=0,
                lastDmgM="",
                lastDmgC="R",
                slDmg=false,
                live=true,                
                anim_acc="",
                anim_col={1,1,1,1},
                items={"pocion", "bomba"},
                ext=0,
                def=false,
                state={},
                tag={},
                hp=10,
                hp_=10,
                mp=5,
                mp_=5,
                sh=0,
                sh_=0,
                gl=0,
                gl_=1,
                agi=3,
                fue=3,
                con=1,
                dex=1,
                ini=0},
                {name="murcielago 3",
                id="murcielago 3",
                id_mons="murcielago",
                tipo="enemy",
                x=380,
                y=272, 
                x_=380,
                y_=272,
                stance="",
                modo="",
                jump_time=0,
                avanzar_time=0,
                attack_time=0,
                react_time=0,
                jump=false,
                rest=true,
                attack=false,
                avanzar=false,
                react=false,
                elemento={"aire","oscuridad","veneno"},
                weak ={fuego="fuego"},
                ventaja={volar="volar"},
                ia={"atacar"},
                p=2,
                anim={ti=0,ac=1,frm={{t=32,spr=3},{t=32,spr=32},}},
                spr=6,
                ico=32,
                lastDmg=0,
                lastDmgM="",
                lastDmgC="R",
                slDmg=false,
                live=true,                
                anim_acc="",
                anim_col={1,1,1,1},
                items={"pocion", "bomba"},
                ext=0,
                def=false,
                state={},
                tag={},
                hp=10,
                hp_=10,
                mp=5,
                mp_=5,
                sh=0,
                sh_=0,
                gl=0,
                gl_=1,
                agi=1,
                fue=3,
                con=1,
                dex=1,
                ini=0},
                },
},
}


horda["bosque_base_01"]={
        {id="grupo 0.1",
                exp=50, credit=50, terrain="pradera", terrain_="pradera", tipo="batalla",fondo="pradera", fondo_="pradera",
                recompensa={"pocion", "ether"},
                enemyList={"murcielago","dummy","murcielago"},
                enemyTeams={},
        },
        
        {id="grupo 0.2",
                exp=50, credit=50, terrain="tierra", terrain_="tierra",tipo="batalla",fondo="pradera",
                recompensa={"pocion", "ether"},
                enemyList={"murcielago","dummy","murcielago"},
                enemyTeams={},
        },
        
        {id="grupo 0.3",
                exp=50, credit=50, terrain="tierra", terrain_="tierra",tipo="batalla",fondo="pradera",
                recompensa={"pocion", "ether"},
                enemyList={"murcielago","dummy","murcielago"},
                enemyTeams={},
        },
}

horda["bosque_base_02"]={
                {id="grupo 0.1",
                exp=50, credit=50, terrain="tierra", terrain_="tierra",tipo="batalla",fondo="pradera",
                recompensa={"pocion", "ether"},
                enemyList={"murcielago","murcielago","murcielago"},
                enemyTeams={},
        },
        
        {id="grupo 0.2",
                exp=50, credit=50, terrain="tierra", terrain_="tierra",tipo="batalla",fondo="pradera",
                recompensa={"pocion", "ether"},
                enemyList={"murcielago","murcielago","murcielago"},
                enemyTeams={},
        },
        
        {id="grupo 0.3",
                exp=50, credit=50, terrain="tierra", terrain_="tierra",tipo="batalla",fondo="pradera",
                recompensa={"pocion", "ether"},
                enemyList={"murcielago","murcielago","murcielago"},
                enemyTeams={},
        },
}



horda["00001"]={

 {id="grupo 0.1",
        exp=50,
        credit=50,
        terrain="agua",
        terrain_="agua",
        tipo="batalla",
        fondo="ocean",
        fondo_="ocean",
        recompensa={"pocion", "ether"},
        enemyList={"murcielago","dummy","murcielago"},
        enemyTeams={                 },
},


        {id="grupo 0.2",
        exp=50,
        credit=50,
        tipo="batalla",
        terrain="tierra",
        terrain_="tierra",
        fondo="pradera",
        fondo_="pradera",
        recompensa={"pocion", "ether"},
        enemyList={"murcielago","murcielago"},
        enemyTeams={                },
},



        {id="grupo 01",
        exp=100,
        credit=100,
        tipo="batalla",
        terrain="pladera",
        terrain_="pladera",
        fondo="pradera",
        fondo_="pradera",
        recompensa={"espada","katana","espada_corta","espada_larga", "pocion", "ether"},
        enemyList={"murcielago","murcielago_fuego","murcielago_hielo"},
        enemyTeams={  },
},


{
        id="grupo 2",
        exp=100,
        credit=100,
        tipo="batalla",
        terrain="cueva",
        terrain_="cueva",
        fondo="cueva",
        fondo_="cueva",
        recompensa={"espada","katana","espada_corta","espada_larga", "pocion", "ether"},
        enemyList={"fuego_fuego","fuego_hielo","fuego_electrico"},
        enemyTeams={},
},
{
        id="grupo 3",
        exp=300,
        credit=300,
        tipo="batalla",
        terrain="agua",
        terrain_="agua",
        fondo="ocean",
        fondo_="ocean",
        recompensa={"espada","katana","espada_corta","espada_larga", "pocion", "ether"},
        enemyList={"murcielago","evil_eye","murcielago"},
        enemyTeams={},
},

{id="standBy 01",
        exp=100,
        credit=100,
        tipo="stand",
        terrain="tierra",
        terrain_="tierra",
        fondo="pradera",
        fondo_="pradera",
        recompensa={"espada","katana","espada_corta","espada_larga", "pocion", "ether"},
        enemyList={},
        enemyTeams={{}},
},

{
        id="grupo 4",
        exp=100,
        credit=100,
        tipo="batalla",
        terrain="pladera",
        terrain_="pladera",
        fondo="pradera",
        fondo_="pradera",
        recompensa={"espada","katana","espada_corta","espada_larga", "pocion", "ether"},
        enemyList={"slime_azul","slime_amarillo","slime_rojo"},
        enemyTeams={},
        },


        {
        id="grupo 5",
        exp=100,
        credit=100,
        tipo="batalla",
        terrain="cueva",
        terrain_="cueva",
        fondo="pradera",
        fondo_="pradera",
        recompensa={"espada","katana","espada_corta","espada_larga", "pocion", "ether"},
        enemyList={"serpiente_verde","Murcielago_electrico","serpiente_purpura"},
        enemyTeams={},
        },


        {
        id="grupo 6",
        exp=100,
        credit=100,
        tipo="batalla",
        terrain="agua",
        terrain_="agua",
        fondo="pradera",
        fondo_="pradera",
        recompensa={"espada","katana","espada_corta","espada_larga", "pocion", "ether"},
        enemyList={"objetos","slime_rainbow","objetos"},
        enemyTeams={},
        },

        {id="standBy 02",
        exp=100,
        credit=100,
        tipo="stand",
        terrain="tierra",
        terrain_="tierra",
        fondo="pradera",
        fondo_="pradera",
        recompensa={"espada","katana","espada_corta","espada_larga", "pocion", "ether"},
        enemyList={},
        enemyTeams={{}},
        },
}

enemyGroups=horda["00001"]




